# Generated by Django 5.0.7 on 2024-08-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_listing_comment_bids"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(
                choices=[
                    ("1", "Art"),
                    ("2", "Books"),
                    ("3", "Collectibles"),
                    ("4", "Electronics"),
                    ("5", "Fashion"),
                    ("6", "Home"),
                    ("7", "Sports"),
                    ("8", "Toys"),
                    ("9", "Vehicles"),
                    ("10", "Food"),
                    ("11", "Other"),
                ],
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="listing_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="starting_bid",
            field=models.PositiveIntegerField(max_length=6),
        ),
    ]
