# Generated by Django 5.0.7 on 2024-08-28 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_watchlist"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="watchlist",
            unique_together={("user", "listing")},
        ),
    ]
