# Generated by Django 5.0.7 on 2024-09-05 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_listing_current_bid_listing_number_of_bids_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="current_bid",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="starting_bid",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
    ]
